import { TravelVibe } from './types';

export interface DestinationMeta {
  city: string;
  country: string;
  countryCode: string;
  flag: string;
  image: string;
  hotelName: string;
  hotelStars: number;
  hotelRating: number;
  hotelNightly: number;
  hotelCenter: string;
  hotelImage: string;
  vibe: TravelVibe;
  temp: number;
  weatherText: string;
  weatherIcon: string;
  dailyCost: number;
  beer: number;
  meal: number;
  coffee: number;
  transport: number;
  description: string;
}

export const DESTINATION_DIRECTORY: Record<string, DestinationMeta> = {
  // ESPAÑA PENINSULAR & BALEARES
  BCN: {
    city: 'Barcelona',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
    hotelName: 'Hotel Barcelona Universal',
    hotelStars: 4,
    hotelRating: 8.7,
    hotelNightly: 29,
    hotelCenter: '400m de Las Ramblas',
    hotelImage: 'https://images.unsplash.com/photo-1618773928121-c32f6e3eea6c?w=600&q=80',
    vibe: 'gastronomy',
    temp: 22,
    weatherText: 'Soleado con brisa mediterránea',
    weatherIcon: '☀️',
    dailyCost: 45,
    beer: 2.8,
    meal: 14.0,
    coffee: 1.6,
    transport: 2.4,
    description: 'Gaudí, playa, barrio Gótico y la mejor vida mediterránea.',
  },
  MAD: {
    city: 'Madrid',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80',
    hotelName: 'Hotel Santo Domingo Gran Vía',
    hotelStars: 4,
    hotelRating: 8.8,
    hotelNightly: 28,
    hotelCenter: 'Pleno centro Gran Vía',
    hotelImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
    vibe: 'culture',
    temp: 20,
    weatherText: 'Cielo despejado',
    weatherIcon: '🌤️',
    dailyCost: 42,
    beer: 2.5,
    meal: 13.5,
    coffee: 1.5,
    transport: 2.0,
    description: 'Museos del Prado, tapas en La Latina, terrazas y musicales en Gran Vía.',
  },
  SVQ: {
    city: 'Sevilla',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1559564484-e48b3e040ff4?w=800&q=80',
    hotelName: 'Hotel Don Paco Sevilla',
    hotelStars: 3,
    hotelRating: 8.9,
    hotelNightly: 25,
    hotelCenter: 'Barrio Santa Cruz',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'culture',
    temp: 25,
    weatherText: 'Cálido y soleado',
    weatherIcon: '☀️',
    dailyCost: 36,
    beer: 2.0,
    meal: 11.0,
    coffee: 1.3,
    transport: 1.8,
    description: 'Plaza de España, Real Alcázar, tapeo en Triana y duende andaluz.',
  },
  VLC: {
    city: 'Valencia',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1512753360435-329c4535a9a7?w=800&q=80',
    hotelName: 'Hotel Dimar Valencia',
    hotelStars: 4,
    hotelRating: 8.6,
    hotelNightly: 27,
    hotelCenter: 'Cerca de Ruzafa y Centro',
    hotelImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
    vibe: 'gastronomy',
    temp: 23,
    weatherText: 'Soleado mediterráneo',
    weatherIcon: '☀️',
    dailyCost: 40,
    beer: 2.2,
    meal: 12.0,
    coffee: 1.4,
    transport: 2.0,
    description: 'Ciudad de las Artes, auténtica paella valenciana, playas y casco histórico.',
  },
  AGP: {
    city: 'Málaga',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80',
    hotelName: 'Hotel Soho Boutique Málaga',
    hotelStars: 3,
    hotelRating: 8.8,
    hotelNightly: 24,
    hotelCenter: 'Calle Larios',
    hotelImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
    vibe: 'sun',
    temp: 24,
    weatherText: 'Soleado en la Costa del Sol',
    weatherIcon: '☀️',
    dailyCost: 35,
    beer: 2.2,
    meal: 12.0,
    coffee: 1.4,
    transport: 1.8,
    description: 'Sol todo el año, espetos en Pedregalejo, museos y ambiente nocturno.',
  },
  BIO: {
    city: 'Bilbao',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80',
    hotelName: 'Hotel Gran Bilbao',
    hotelStars: 4,
    hotelRating: 8.8,
    hotelNightly: 28,
    hotelCenter: 'Cerca del Casco Viejo',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'gastronomy',
    temp: 19,
    weatherText: 'Templado norteño',
    weatherIcon: '🌤️',
    dailyCost: 44,
    beer: 2.8,
    meal: 14.5,
    coffee: 1.6,
    transport: 2.0,
    description: 'Museo Guggenheim, ruta de pintxos por el Casco Viejo y ría de Bilbao.',
  },
  SCQ: {
    city: 'Santiago de Compostela',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1574870111867-089730e5a72b?w=800&q=80',
    hotelName: 'Hotel Gelmírez',
    hotelStars: 3,
    hotelRating: 8.7,
    hotelNightly: 26,
    hotelCenter: '300m de la Plaza del Obradoiro',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'culture',
    temp: 18,
    weatherText: 'Fresco y agradable',
    weatherIcon: '🌤️',
    dailyCost: 38,
    beer: 2.2,
    meal: 12.0,
    coffee: 1.4,
    transport: 1.8,
    description: 'Catedral de Santiago, casco histórico de piedra, marisco gallego y albariño.',
  },
  ALC: {
    city: 'Alicante',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1592861956120-e524fc739696?w=800&q=80',
    hotelName: 'Hotel Maya Alicante',
    hotelStars: 3,
    hotelRating: 8.5,
    hotelNightly: 25,
    hotelCenter: 'Cerca del Castillo de Santa Bárbara',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'sun',
    temp: 23,
    weatherText: 'Soleado mediterráneo',
    weatherIcon: '☀️',
    dailyCost: 36,
    beer: 2.0,
    meal: 11.5,
    coffee: 1.3,
    transport: 1.8,
    description: 'Castillo de Santa Bárbara, paseo de la Explanada y arroces alicantinos.',
  },
  PMI: {
    city: 'Mallorca',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    hotelName: 'Hotel Saratoga Palma Centro',
    hotelStars: 4,
    hotelRating: 8.9,
    hotelNightly: 30,
    hotelCenter: 'Paseo Mallorca céntrico',
    hotelImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
    vibe: 'sun',
    temp: 23,
    weatherText: 'Soleado balear',
    weatherIcon: '☀️',
    dailyCost: 42,
    beer: 2.5,
    meal: 13.5,
    coffee: 1.6,
    transport: 2.0,
    description: 'Calas cristalinas, Sierra de Tramuntana, ensaimadas y casco histórico de Palma.',
  },
  IBZ: {
    city: 'Ibiza',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1512353087810-25dfcd100962?w=800&q=80',
    hotelName: 'Hotel Royal Plaza Ibiza',
    hotelStars: 4,
    hotelRating: 8.6,
    hotelNightly: 34,
    hotelCenter: 'Dalt Vila / Centro',
    hotelImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
    vibe: 'nightlife',
    temp: 23,
    weatherText: 'Templado balear',
    weatherIcon: '☀️',
    dailyCost: 52,
    beer: 3.5,
    meal: 16.0,
    coffee: 2.0,
    transport: 2.5,
    description: 'Atardeceres en Café del Mar, calas turquesas y patrimonio histórico en Dalt Vila.',
  },
  MAH: {
    city: 'Menorca',
    country: 'España',
    countryCode: 'ES',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    hotelName: 'Hotel Port Mahón',
    hotelStars: 4,
    hotelRating: 8.8,
    hotelNightly: 32,
    hotelCenter: 'Puerto de Mahón',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'romantic',
    temp: 22,
    weatherText: 'Tranquilo y soleado',
    weatherIcon: '☀️',
    dailyCost: 44,
    beer: 2.5,
    meal: 14.0,
    coffee: 1.5,
    transport: 2.0,
    description: 'Calas vírgenes de arena blanca, Camí de Cavalls y tranquilidad absoluta.',
  },

  // CANARIAS INTERINSULARES
  LPA: {
    city: 'Gran Canaria',
    country: 'España',
    countryCode: 'ES',
    flag: '🇮🇨',
    image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
    hotelName: 'Hotel Santa Catalina Gran Canaria',
    hotelStars: 5,
    hotelRating: 9.2,
    hotelNightly: 35,
    hotelCenter: 'Ciudad Jardín / Las Palmas',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'sun',
    temp: 24,
    weatherText: 'Primavera eterna',
    weatherIcon: '☀️',
    dailyCost: 34,
    beer: 1.8,
    meal: 11.0,
    coffee: 1.2,
    transport: 1.4,
    description: 'Dunas de Maspalomas, barrio histórico de Vegueta y playas doradas.',
  },
  ACE: {
    city: 'Lanzarote',
    country: 'España',
    countryCode: 'ES',
    flag: '🇮🇨',
    image: 'https://images.unsplash.com/photo-1580237072617-771c3ecc4a24?w=800&q=80',
    hotelName: 'Boutique Hotel H10 Timanfaya',
    hotelStars: 4,
    hotelRating: 8.9,
    hotelNightly: 32,
    hotelCenter: 'Playa Blanca',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'sun',
    temp: 23,
    weatherText: 'Soleado volcánico',
    weatherIcon: '☀️',
    dailyCost: 33,
    beer: 2.0,
    meal: 12.0,
    coffee: 1.3,
    transport: 1.5,
    description: 'Paisajes lunares de Timanfaya, arquitectura de César Manrique y playas vírgenes.',
  },
  TFS: {
    city: 'Tenerife',
    country: 'España',
    countryCode: 'ES',
    flag: '🇮🇨',
    image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
    hotelName: 'Hotel Botánico & Oriental Spa',
    hotelStars: 5,
    hotelRating: 9.3,
    hotelNightly: 36,
    hotelCenter: 'Puerto de la Cruz',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'sun',
    temp: 24,
    weatherText: 'Cálido y templado',
    weatherIcon: '☀️',
    dailyCost: 35,
    beer: 1.8,
    meal: 11.5,
    coffee: 1.2,
    transport: 1.5,
    description: 'Parque Nacional del Teide, playas de arena negra y gastronomía en guachinches.',
  },
  TFN: {
    city: 'Tenerife Norte',
    country: 'España',
    countryCode: 'ES',
    flag: '🇮🇨',
    image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
    hotelName: 'Hotel Laguna Nivaria',
    hotelStars: 4,
    hotelRating: 9.0,
    hotelNightly: 33,
    hotelCenter: 'La Laguna Patrimonio Unesco',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'culture',
    temp: 21,
    weatherText: 'Fresco agradable',
    weatherIcon: '🌤️',
    dailyCost: 34,
    beer: 1.8,
    meal: 11.0,
    coffee: 1.2,
    transport: 1.4,
    description: 'La Laguna histórica, bosques de Anaga y auténtico sabor canario.',
  },
  FUE: {
    city: 'Fuerteventura',
    country: 'España',
    countryCode: 'ES',
    flag: '🇮🇨',
    image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80',
    hotelName: 'Hotel Riu Palace Tres Islas',
    hotelStars: 4,
    hotelRating: 8.9,
    hotelNightly: 34,
    hotelCenter: 'Grandes Playas de Corralejo',
    hotelImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
    vibe: 'sun',
    temp: 24,
    weatherText: 'Brisa y sol radiante',
    weatherIcon: '☀️',
    dailyCost: 34,
    beer: 2.0,
    meal: 12.0,
    coffee: 1.3,
    transport: 1.5,
    description: 'Kilómetros de playas paradisíacas de arena blanca, dunas y aguas turquesas.',
  },
  SPC: {
    city: 'La Palma',
    country: 'España',
    countryCode: 'ES',
    flag: '🇮🇨',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    hotelName: 'Hotel H10 Taburiente Playa',
    hotelStars: 4,
    hotelRating: 8.8,
    hotelNightly: 30,
    hotelCenter: 'Los Cancajos',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'culture',
    temp: 22,
    weatherText: 'Naturaleza pura',
    weatherIcon: '🌤️',
    dailyCost: 32,
    beer: 1.8,
    meal: 11.0,
    coffee: 1.2,
    transport: 1.4,
    description: 'La Isla Bonita: Caldera de Taburiente, cielos estrellados y senderos verdes.',
  },

  // PORTUGAL & MARRUECOS
  OPO: {
    city: 'Oporto',
    country: 'Portugal',
    countryCode: 'PT',
    flag: '🇵🇹',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    hotelName: 'Porto Ribeira Boutique',
    hotelStars: 4,
    hotelRating: 9.1,
    hotelNightly: 26,
    hotelCenter: '250m de la Ribeira',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'romantic',
    temp: 21,
    weatherText: 'Agradable y templado',
    weatherIcon: '🌤️',
    dailyCost: 38,
    beer: 2.0,
    meal: 11.5,
    coffee: 1.2,
    transport: 1.8,
    description: 'Vinos de Oporto, puentes sobre el río Duero, fado y gastronomía portuguesa.',
  },
  LIS: {
    city: 'Lisboa',
    country: 'Portugal',
    countryCode: 'PT',
    flag: '🇵🇹',
    image: 'https://images.unsplash.com/photo-1513581166391-887a96ddeafd?w=800&q=80',
    hotelName: 'Hotel Lis Baixa',
    hotelStars: 3,
    hotelRating: 8.9,
    hotelNightly: 29,
    hotelCenter: 'Baixa Pombalina',
    hotelImage: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600&q=80',
    vibe: 'romantic',
    temp: 22,
    weatherText: 'Brisa del Atlántico',
    weatherIcon: '🌤️',
    dailyCost: 39,
    beer: 2.2,
    meal: 12.0,
    coffee: 1.2,
    transport: 1.8,
    description: 'Tranvía 28, miradores románticos, pasteles de Belém y fado en Alfama.',
  },
  FNC: {
    city: 'Madeira',
    country: 'Portugal',
    countryCode: 'PT',
    flag: '🇵🇹',
    image: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800&q=80',
    hotelName: 'Hotel Quinta da Penha de França',
    hotelStars: 4,
    hotelRating: 9.0,
    hotelNightly: 32,
    hotelCenter: 'Funchal Centro',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'romantic',
    temp: 22,
    weatherText: 'Eterna primavera',
    weatherIcon: '🌤️',
    dailyCost: 38,
    beer: 2.0,
    meal: 12.0,
    coffee: 1.2,
    transport: 1.6,
    description: 'Levadas verdes, acantilados imponentes sobre el Atlántico y flores tropicales.',
  },
  RAK: {
    city: 'Marrakech',
    country: 'Marruecos',
    countryCode: 'MA',
    flag: '🇲🇦',
    image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800&q=80',
    hotelName: 'Riad Jasmine & Spa',
    hotelStars: 4,
    hotelRating: 9.3,
    hotelNightly: 22,
    hotelCenter: 'Medina de Marrakech',
    hotelImage: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
    vibe: 'culture',
    temp: 26,
    weatherText: 'Cálido y exótico',
    weatherIcon: '☀️',
    dailyCost: 28,
    beer: 3.0,
    meal: 8.0,
    coffee: 1.0,
    transport: 1.5,
    description: 'Plaza Jemaa el-Fna, zocos aromáticos, palacios y té a la menta.',
  },
  AGA: {
    city: 'Agadir',
    country: 'Marruecos',
    countryCode: 'MA',
    flag: '🇲🇦',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80',
    hotelName: 'Hotel Timoulay and Spa Agadir',
    hotelStars: 4,
    hotelRating: 8.8,
    hotelNightly: 24,
    hotelCenter: 'Paseo Marítimo de Agadir',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'sun',
    temp: 25,
    weatherText: 'Sol y costa atlántica',
    weatherIcon: '☀️',
    dailyCost: 26,
    beer: 3.0,
    meal: 7.5,
    coffee: 1.0,
    transport: 1.2,
    description: 'Playas infinitas, surf, zoco El Had y excelente gastronomía bereber.',
  },

  // ITALIA
  ROM: {
    city: 'Roma',
    country: 'Italia',
    countryCode: 'IT',
    flag: '🇮🇹',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    hotelName: 'Hotel Raffaello Trastevere',
    hotelStars: 3,
    hotelRating: 8.6,
    hotelNightly: 32,
    hotelCenter: 'Trastevere',
    hotelImage: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=600&q=80',
    vibe: 'romantic',
    temp: 21,
    weatherText: 'Cielo claro',
    weatherIcon: '☀️',
    dailyCost: 48,
    beer: 3.5,
    meal: 15.0,
    coffee: 1.5,
    transport: 2.5,
    description: 'Coliseo, Fontana di Trevi, pasta carbonara auténtica y rincones mágicos.',
  },
  MIL: {
    city: 'Milán',
    country: 'Italia',
    countryCode: 'IT',
    flag: '🇮🇹',
    image: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800&q=80',
    hotelName: 'Hotel Glam Milano',
    hotelStars: 4,
    hotelRating: 8.7,
    hotelNightly: 34,
    hotelCenter: 'Duomo / Centro',
    hotelImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
    vibe: 'culture',
    temp: 19,
    weatherText: 'Templado y chic',
    weatherIcon: '🌤️',
    dailyCost: 52,
    beer: 4.0,
    meal: 16.0,
    coffee: 1.8,
    transport: 2.2,
    description: 'Duomo di Milano, Galería Vittorio Emanuele, moda y aperitivo italiano.',
  },
  VCE: {
    city: 'Venecia',
    country: 'Italia',
    countryCode: 'IT',
    flag: '🇮🇹',
    image: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800&q=80',
    hotelName: 'Hotel Rialto Venezia',
    hotelStars: 4,
    hotelRating: 8.7,
    hotelNightly: 36,
    hotelCenter: 'Junto al Puente de Rialto',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'romantic',
    temp: 20,
    weatherText: 'Romántico sobre canales',
    weatherIcon: '🌤️',
    dailyCost: 50,
    beer: 3.8,
    meal: 16.0,
    coffee: 2.0,
    transport: 3.0,
    description: 'Plaza San Marcos, paseo en góndola por el Gran Canal y romanticismo.',
  },
  NAP: {
    city: 'Nápoles',
    country: 'Italia',
    countryCode: 'IT',
    flag: '🇮🇹',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80',
    hotelName: 'Hotel Piazza Bellini & Relais',
    hotelStars: 3,
    hotelRating: 8.9,
    hotelNightly: 27,
    hotelCenter: 'Centro Histórico',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'gastronomy',
    temp: 22,
    weatherText: 'Soleado campano',
    weatherIcon: '☀️',
    dailyCost: 36,
    beer: 2.5,
    meal: 11.0,
    coffee: 1.2,
    transport: 1.6,
    description: 'La cuna de la pizza napolitana auténtica, vistas al Vesubio y caos encantador.',
  },

  // FRANCIA
  PAR: {
    city: 'París',
    country: 'Francia',
    countryCode: 'FR',
    flag: '🇫🇷',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    hotelName: 'Hotel Eiffel Seine',
    hotelStars: 3,
    hotelRating: 8.6,
    hotelNightly: 38,
    hotelCenter: 'Junto al río Sena',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'romantic',
    temp: 19,
    weatherText: 'Romántico y templado',
    weatherIcon: '🌤️',
    dailyCost: 55,
    beer: 4.5,
    meal: 18.0,
    coffee: 2.8,
    transport: 2.8,
    description: 'Torre Eiffel, Museo del Louvre, Montmartre, croissants y paseos por el Sena.',
  },
  NTE: {
    city: 'Nantes',
    country: 'Francia',
    countryCode: 'FR',
    flag: '🇫🇷',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    hotelName: 'Hotel Mercure Nantes Centre',
    hotelStars: 4,
    hotelRating: 8.7,
    hotelNightly: 30,
    hotelCenter: 'Centro Histórico Nantes',
    hotelImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
    vibe: 'culture',
    temp: 18,
    weatherText: 'Agradable y templado',
    weatherIcon: '🌤️',
    dailyCost: 44,
    beer: 3.5,
    meal: 14.5,
    coffee: 2.2,
    transport: 2.0,
    description: 'Las Máquinas de la Isla, el elefante gigante, castillos del Loira y arte.',
  },
  NCE: {
    city: 'Niza',
    country: 'Francia',
    countryCode: 'FR',
    flag: '🇫🇷',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80',
    hotelName: 'Hotel Le Meurice Nice',
    hotelStars: 3,
    hotelRating: 8.8,
    hotelNightly: 35,
    hotelCenter: 'Promenade des Anglais',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'sun',
    temp: 23,
    weatherText: 'Costa Azul soleada',
    weatherIcon: '☀️',
    dailyCost: 52,
    beer: 4.5,
    meal: 17.0,
    coffee: 2.5,
    transport: 2.2,
    description: 'Promenade des Anglais, aguas turquesas de la Costa Azul y glamour provenzal.',
  },

  // REINO UNIDO & IRLANDA
  LON: {
    city: 'Londres',
    country: 'Reino Unido',
    countryCode: 'GB',
    flag: '🇬🇧',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
    hotelName: 'The Corner Hotel London',
    hotelStars: 3,
    hotelRating: 8.7,
    hotelNightly: 39,
    hotelCenter: 'Zona 1 de Londres',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'culture',
    temp: 17,
    weatherText: 'Típico clima británico',
    weatherIcon: '🌤️',
    dailyCost: 58,
    beer: 5.0,
    meal: 18.0,
    coffee: 3.2,
    transport: 3.2,
    description: 'Big Ben, museos gratuitos, mercadillos de Camden y musicales en West End.',
  },
  DUB: {
    city: 'Dublín',
    country: 'Irlanda',
    countryCode: 'IE',
    flag: '🇮🇪',
    image: 'https://images.unsplash.com/photo-1549918864-48ac978761a4?w=800&q=80',
    hotelName: 'Academy Plaza Hotel Dublin',
    hotelStars: 3,
    hotelRating: 8.6,
    hotelNightly: 36,
    hotelCenter: 'Temple Bar céntrico',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'nightlife',
    temp: 16,
    weatherText: 'Templado irlandés',
    weatherIcon: '🌤️',
    dailyCost: 54,
    beer: 5.5,
    meal: 17.0,
    coffee: 3.0,
    transport: 2.6,
    description: 'Temple Bar, música en directo, fábrica Guinness y hospitalidad irlandesa.',
  },
  MAN: {
    city: 'Manchester',
    country: 'Reino Unido',
    countryCode: 'GB',
    flag: '🇬🇧',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
    hotelName: 'Motel One Manchester-Piccadilly',
    hotelStars: 3,
    hotelRating: 8.8,
    hotelNightly: 32,
    hotelCenter: 'Northern Quarter',
    hotelImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
    vibe: 'nightlife',
    temp: 16,
    weatherText: 'Fresco británico',
    weatherIcon: '🌤️',
    dailyCost: 48,
    beer: 4.5,
    meal: 15.0,
    coffee: 2.8,
    transport: 2.8,
    description: 'Northern Quarter, música britpop, fútbol de élite y ambiente industrial moderno.',
  },

  // CENTROEUROPA
  BER: {
    city: 'Berlín',
    country: 'Alemania',
    countryCode: 'DE',
    flag: '🇩🇪',
    image: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80',
    hotelName: 'Motel One Berlin-Alexanderplatz',
    hotelStars: 3,
    hotelRating: 8.8,
    hotelNightly: 32,
    hotelCenter: 'Mitte / Alexanderplatz',
    hotelImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
    vibe: 'nightlife',
    temp: 18,
    weatherText: 'Fresco cosmopolita',
    weatherIcon: '🌤️',
    dailyCost: 46,
    beer: 3.5,
    meal: 14.0,
    coffee: 2.5,
    transport: 2.6,
    description: 'Puerta de Brandeburgo, Muro de Berlín, arte urbano y la mejor vida nocturna.',
  },
  AMS: {
    city: 'Ámsterdam',
    country: 'Países Bajos',
    countryCode: 'NL',
    flag: '🇳🇱',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80',
    hotelName: 'Hotel V Frederiksplein',
    hotelStars: 3,
    hotelRating: 8.9,
    hotelNightly: 38,
    hotelCenter: 'Junto a los canales',
    hotelImage: 'https://images.unsplash.com/photo-1618773928121-c32f6e3eea6c?w=600&q=80',
    vibe: 'nightlife',
    temp: 17,
    weatherText: 'Templado y fresco',
    weatherIcon: '🌤️',
    dailyCost: 54,
    beer: 4.5,
    meal: 16.0,
    coffee: 3.0,
    transport: 2.8,
    description: 'Canales históricos, paseos en bicicleta, Museo Van Gogh y flores.',
  },
  VIE: {
    city: 'Viena',
    country: 'Austria',
    countryCode: 'AT',
    flag: '🇦🇹',
    image: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80',
    hotelName: 'Hotel Regina Viena',
    hotelStars: 4,
    hotelRating: 8.9,
    hotelNightly: 35,
    hotelCenter: 'Ringstraße céntrico',
    hotelImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
    vibe: 'culture',
    temp: 18,
    weatherText: 'Fresco imperial',
    weatherIcon: '🌤️',
    dailyCost: 52,
    beer: 4.0,
    meal: 16.0,
    coffee: 3.5,
    transport: 2.6,
    description: 'Palacios de Schönbrunn, música clásica, tarta Sacher y elegancia imperial.',
  },
  BRU: {
    city: 'Bruselas',
    country: 'Bélgica',
    countryCode: 'BE',
    flag: '🇧🇪',
    image: 'https://images.unsplash.com/photo-1559113202-c916b8e44373?w=800&q=80',
    hotelName: 'Motel One Brussels',
    hotelStars: 3,
    hotelRating: 8.8,
    hotelNightly: 32,
    hotelCenter: 'Grand Place céntrico',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'gastronomy',
    temp: 17,
    weatherText: 'Templado belga',
    weatherIcon: '🌤️',
    dailyCost: 48,
    beer: 4.0,
    meal: 15.0,
    coffee: 2.8,
    transport: 2.4,
    description: 'Grand Place iluminada, gofres belgas, chocolate artesanal y cervezas trapenses.',
  },
  PRG: {
    city: 'Praga',
    country: 'República Checa',
    countryCode: 'CZ',
    flag: '🇨🇿',
    image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80',
    hotelName: 'Hotel Caruso Prague',
    hotelStars: 4,
    hotelRating: 9.0,
    hotelNightly: 28,
    hotelCenter: 'Barrio Judío / Ciudad Vieja',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    vibe: 'romantic',
    temp: 17,
    weatherText: 'Cuento de hadas',
    weatherIcon: '🌤️',
    dailyCost: 36,
    beer: 2.0,
    meal: 11.0,
    coffee: 2.0,
    transport: 1.5,
    description: 'Puente de Carlos, Castillo de Praga, reloj astronómico y cerveza checa legendaria.',
  },
  BUD: {
    city: 'Budapest',
    country: 'Hungría',
    countryCode: 'HU',
    flag: '🇭🇺',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&q=80',
    hotelName: 'Hotel Moments Budapest',
    hotelStars: 4,
    hotelRating: 9.2,
    hotelNightly: 26,
    hotelCenter: 'Avenida Andrássy céntrico',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'romantic',
    temp: 18,
    weatherText: 'Fresco a orillas del Danubio',
    weatherIcon: '🌤️',
    dailyCost: 32,
    beer: 1.8,
    meal: 10.0,
    coffee: 1.6,
    transport: 1.2,
    description: 'Balnearios termales Széchenyi, Parlamento sobre el Danubio y Ruin Bars mágicos.',
  },
  WAW: {
    city: 'Varsovia',
    country: 'Polonia',
    countryCode: 'PL',
    flag: '🇵🇱',
    image: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=800&q=80',
    hotelName: 'Hotel Bristol Warsaw',
    hotelStars: 4,
    hotelRating: 9.0,
    hotelNightly: 25,
    hotelCenter: 'Casco Histórico Real',
    hotelImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
    vibe: 'culture',
    temp: 16,
    weatherText: 'Fresco agradable',
    weatherIcon: '🌤️',
    dailyCost: 32,
    beer: 2.0,
    meal: 9.5,
    coffee: 1.8,
    transport: 1.2,
    description: 'Ciudad Vieja reconstruida, palacios reales, gastronomía polaca asequible.',
  },
};

/**
 * Resolver for destination metadata.
 * Returns metadata ONLY for known, verified holiday destinations.
 */
export function resolveDestinationMeta(iata: string): DestinationMeta | null {
  const cleanIata = (iata || '').toUpperCase().trim();
  return DESTINATION_DIRECTORY[cleanIata] || null;
}
