// ========================================
// TRAVELDISCOVERY — MOCK DATA (12 DESTINATIONS)
// With Vibes, Destination Cost Index, 3-Day Itineraries, Weather, and Airbnb / Hotel Switch
// ========================================

import { TripCombination } from './types';

export const MOCK_TRIPS: TripCombination[] = [
  {
    id: 'trip-bcn-001',
    destination: {
      city: 'Barcelona',
      country: 'España',
      countryCode: 'ES',
      flag: '🇪🇸',
      image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
      description: 'Gaudí, playa, barrio Gótico y la mejor vida mediterránea.',
    },
    outboundFlight: {
      departure: '2026-10-12T08:00:00',
      arrival: '2026-10-12T12:45:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'BCN', name: 'El Prat', city: 'Barcelona' },
      airline: 'Vueling',
      flightNumber: 'VY2374',
      duration: '2h 45m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-15T20:00:00',
      arrival: '2026-10-15T22:45:00',
      origin: { code: 'BCN', name: 'El Prat', city: 'Barcelona' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Vueling',
      flightNumber: 'VY2375',
      duration: '2h 45m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Hotel Barcelona Universal 4★',
      type: 'hotel',
      stars: 4,
      rating: 8.7,
      ratingLabel: 'Fabuloso',
      reviewCount: 6890,
      distanceFromCenter: '400m de Las Ramblas',
      image: 'https://images.unsplash.com/photo-1618773928121-c32f6e3eea6c?w=600&q=80',
      nightlyRate: 29,
      totalPrice: 87,
      freeCancellation: true,
      breakfastIncluded: true,
      bookingPlatform: 'Booking',
      propertyType: 'Hotel 4 Estrellas',
    },
    flightPrice: 42,
    hotelPrice: 87,
    totalPrice: 129,
    nights: 3,
    tripScore: 97,
    scores: { price: 98, hotel: 94, flight: 98, convenience: 95, destination: 96 },
    aiExplanation: 'Nuestra recomendación nº 1. Hotel 4 estrellas con desayuno buffet a pasos de Las Ramblas por solo 129 €. Una ganga absoluta con vuelo directo.',
    tags: ['⭐ Recomendado nº 1', '✈️ Vuelo Directo', '🥐 Desayuno Buffet', '🏨 4 Estrellas'],
    vibe: 'gastronomy',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 45,
      beerPrice: 2.8,
      mealPrice: 14.0,
      coffeePrice: 1.6,
      transportPrice: 2.4,
      costTier: 'medium',
    },
    weather: { temp: 22, text: 'Soleado con brisa marina', icon: '☀️' },
    itinerary: [
      {
        day: 1,
        title: 'Llegada, Barrio Gótico & Tapas en El Born',
        morning: 'Llegada en vuelo matutino, check-in y paseo por la Plaza Real.',
        afternoon: 'Paseo por las callejuelas medievales del Barrio Gótico y la Catedral de Barcelona.',
        evening: 'Ruta de tapas y vinos en El Born (degustación de pan con tomate y jamón ibérico).',
        tip: 'Toma el metro L3 directamente en Drassanes para moverte sin taxis.',
      },
      {
        day: 2,
        title: 'Día Modernista: Sagrada Familia & Parque Güell',
        morning: 'Visita prioritaria a la Sagrada Familia y el interior iluminado por vidrieras.',
        afternoon: 'Paseo por el Paseo de Gracia admirando la Casa Batlló y La Pedrera.',
        evening: 'Atardecer panorámico en los Bunkers del Carmel o la playa de la Barceloneta.',
        tip: 'Reserva la entrada de la Sagrada Familia a primera hora para evitar aglomeraciones.',
      },
      {
        day: 3,
        title: 'Mercado de la Boquería & Vuelo de Regreso',
        morning: 'Desayuno en el hotel y visita de aromas en el Mercado de la Boquería.',
        afternoon: 'Paseo marítimo por el Port Vell y compras en Portal de l’Àngel.',
        evening: 'Vuelo directo de vuelta a Canarias con las maletas llenas de recuerdos.',
        tip: 'El Aerobús sale cada 5 minutos desde Plaza Cataluña al aeropuerto.',
      },
    ],
    curatedActivity: { name: 'Tour gastronómico por el Gótico', price: 32, duration: '3h', rating: 9.4 },
    activities: [
      { name: 'Sagrada Familia (entrada rápida)', price: 26, duration: '1.5h', rating: 9.8 },
      { name: 'Tour gastronómico por el Gótico', price: 32, duration: '3h', rating: 9.4 },
    ],
    savedByUsers: 891,
    priceDropped: true,
    previousPrice: 158,
  },
  {
    id: 'trip-mad-001',
    destination: {
      city: 'Madrid',
      country: 'España',
      countryCode: 'ES',
      flag: '🇪🇸',
      image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80',
      description: 'La capital nunca defrauda. Museos, tapas y vida nocturna.',
    },
    outboundFlight: {
      departure: '2026-10-12T07:15:00',
      arrival: '2026-10-12T11:30:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'MAD', name: 'Barajas', city: 'Madrid' },
      airline: 'Ryanair',
      flightNumber: 'FR2841',
      duration: '2h 45m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-15T18:40:00',
      arrival: '2026-10-15T21:20:00',
      origin: { code: 'MAD', name: 'Barajas', city: 'Madrid' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Ryanair',
      flightNumber: 'FR2842',
      duration: '2h 40m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Hotel Petit Palace Chueca',
      type: 'hotel',
      stars: 3,
      rating: 8.5,
      ratingLabel: 'Muy bien',
      reviewCount: 2847,
      distanceFromCenter: '300m de Gran Vía',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      nightlyRate: 28,
      totalPrice: 84,
      freeCancellation: true,
      breakfastIncluded: false,
      bookingPlatform: 'Booking',
      propertyType: 'Hotel Boutique',
    },
    flightPrice: 38,
    hotelPrice: 84,
    totalPrice: 122,
    nights: 3,
    tripScore: 94,
    scores: { price: 96, hotel: 88, flight: 100, convenience: 95, destination: 90 },
    aiExplanation: 'La mejor relación calidad-precio. Vuelo directo con horarios perfectos para aprovechar los 3 días enteros. Hotel a 5 minutos de Gran Vía.',
    tags: ['✈️ Directo', '⭐ Precio Mínimo', '📍 A 5 min Gran Vía', '🏨 Hotel Boutique'],
    vibe: 'culture',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 42,
      beerPrice: 2.5,
      mealPrice: 13.0,
      coffeePrice: 1.5,
      transportPrice: 1.5,
      costTier: 'medium',
    },
    weather: { temp: 20, text: 'Agradable y soleado', icon: '☀️' },
    itinerary: [
      {
        day: 1,
        title: 'Gran Vía, Puerta del Sol y Plaza Mayor',
        morning: 'Llegada temprana, paseo por la Gran Vía y chocolate con churros en San Ginés.',
        afternoon: 'Visita a la Plaza Mayor y paseo por el Palacio Real y los Jardines de Sabatini.',
        evening: 'Ruta de cañas y pinchos por el animado barrio de La Latina.',
        tip: 'El metro te lleva de Barajas al centro en solo 25 minutos.',
      },
      {
        day: 2,
        title: 'El Triángulo del Arte y El Retiro',
        morning: 'Visita al Museo del Prado con las obras maestras de Velázquez y Goya.',
        afternoon: 'Paseo relajante en barca por el estanque del Parque del Buen Retiro y Palacio de Cristal.',
        evening: 'Atardecer en el Templo de Debod con vistas a la sierra y cena en Malasaña.',
        tip: 'El Retiro es Patrimonio Mundial de la UNESCO y es gratuito.',
      },
      {
        day: 3,
        title: 'Mercado de San Miguel & Regreso',
        morning: 'Degustación gourmet en el Mercado de San Miguel y compras en Fuencarral.',
        afternoon: 'Últimas fotos en la terraza del Círculo de Bellas Artes.',
        evening: 'Vuelo directo de vuelta a las islas al anochecer.',
        tip: 'Sube a la azotea de Bellas Artes para la foto icónica de Gran Vía.',
      },
    ],
    curatedActivity: { name: 'Museo del Prado (acceso rápido)', price: 15, duration: '3h', rating: 9.6 },
    activities: [
      { name: 'Museo del Prado (entrada rápida)', price: 15, duration: '3h', rating: 9.6 },
      { name: 'Tour de tapas por La Latina', price: 28, duration: '2.5h', rating: 9.2 },
    ],
    savedByUsers: 540,
  },
  {
    id: 'trip-opo-001',
    destination: {
      city: 'Oporto',
      country: 'Portugal',
      countryCode: 'PT',
      flag: '🇵🇹',
      image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
      description: 'Bodegas de vino, puentes sobre el Duero y gastronomía exquisita.',
    },
    outboundFlight: {
      departure: '2026-10-14T09:10:00',
      arrival: '2026-10-14T11:45:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'OPO', name: 'Francisco Sá Carneiro', city: 'Oporto' },
      airline: 'Ryanair',
      flightNumber: 'FR2084',
      duration: '2h 35m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-17T17:20:00',
      arrival: '2026-10-17T19:55:00',
      origin: { code: 'OPO', name: 'Francisco Sá Carneiro', city: 'Oporto' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Ryanair',
      flightNumber: 'FR2085',
      duration: '2h 35m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Loft Ribeira Duero Airbnb Superhost',
      type: 'apartment',
      isAirbnb: true,
      superhost: true,
      hasKitchen: true,
      stars: 4,
      rating: 9.6,
      ratingLabel: 'Superhost ⭐',
      reviewCount: 3120,
      distanceFromCenter: '150m de la Ribeira',
      image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=600&q=80',
      nightlyRate: 26,
      totalPrice: 78,
      freeCancellation: true,
      breakfastIncluded: false,
      bookingPlatform: 'Airbnb',
      propertyType: 'Loft completo con cocina & balcón',
    },
    flightPrice: 40,
    hotelPrice: 78,
    totalPrice: 118,
    nights: 3,
    tripScore: 95,
    scores: { price: 98, hotel: 96, flight: 94, convenience: 92, destination: 95 },
    aiExplanation: 'Una joya económica en Airbnb. Vuelo directo y loft de diseño frente al Duero con cocina equipada por solo 118 € en total. Ciudad muy barata para comer y pasear.',
    tags: ['🔥 Ganga 118€', '✈️ Directo', '🏡 Airbnb Plus', '🍳 Cocina propia', '🍷 Ribeira'],
    vibe: 'romantic',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 32,
      beerPrice: 1.8,
      mealPrice: 9.5,
      coffeePrice: 0.9,
      transportPrice: 1.2,
      costTier: 'low',
    },
    weather: { temp: 21, text: 'Cálido y agradable', icon: '🌤️' },
    itinerary: [
      {
        day: 1,
        title: 'Llegada, Puente Luis I & Paseo por Ribeira',
        morning: 'Aterrizaje en Oporto, check-in en el loft y primer café con pastel de nata.',
        afternoon: 'Cruce a pie por la pasarela superior del Puente Don Luis I con vistas espectaculares.',
        evening: 'Cena a orillas del Duero: una auténtica francesinha tradicional regada con vino verde.',
        tip: 'La tarjeta Andante Tour de metro es muy económica.',
      },
      {
        day: 2,
        title: 'Bodegas de Gaia & Librería Lello',
        morning: 'Visita a la famosa Livraria Lello y la Torre de los Clérigos.',
        afternoon: 'Crucero de los 6 puentes en barco rabelo y cata en las bodegas de Vila Nova de Gaia.',
        evening: 'Atardecer en el Mirador de Serra do Pilar con copa de vino de Oporto.',
        tip: 'Reserva la visita a las bodegas con antelación para incluir la cata de tinto y tawny.',
      },
      {
        day: 3,
        title: 'Barrio de Foz & Puesta de Sol en el Atlántico',
        morning: 'Tranvía histórico nº 1 bordeando el río hasta la desembocadura en Foz do Douro.',
        afternoon: 'Paseo por el paseo marítimo del Atlántico y compras de azulejos artesanales.',
        evening: 'Regreso al aeropuerto con un viaje inolvidable y súper barato.',
        tip: 'El metro te conecta directo de la estación de Trindade al aeropuerto en 25 min.',
      },
    ],
    curatedActivity: { name: 'Crucero 6 puentes por el Duero', price: 15, duration: '1h', rating: 9.5 },
    activities: [
      { name: 'Crucero 6 puentes por el Duero', price: 15, duration: '1h', rating: 9.5 },
      { name: 'Cata de vinos en Bodega Cálem', price: 18, duration: '1.5h', rating: 9.3 },
    ],
    savedByUsers: 720,
    priceDropped: true,
    previousPrice: 145,
  },
  {
    id: 'trip-agp-001',
    destination: {
      city: 'Málaga',
      country: 'España',
      countryCode: 'ES',
      flag: '🇪🇸',
      image: 'https://images.unsplash.com/photo-1579282240050-352db0a14c21?w=800&q=80',
      description: 'Costa del Sol, arte, espetos de sardinas y ambiente inmejorable.',
    },
    outboundFlight: {
      departure: '2026-10-13T06:30:00',
      arrival: '2026-10-13T09:55:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'AGP', name: 'Costa del Sol', city: 'Málaga' },
      airline: 'Vueling',
      flightNumber: 'VY3118',
      duration: '2h 25m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-16T21:40:00',
      arrival: '2026-10-16T23:10:00',
      origin: { code: 'AGP', name: 'Costa del Sol', city: 'Málaga' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Vueling',
      flightNumber: 'VY3119',
      duration: '2h 30m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Ático Soleado Calle Larios Airbnb',
      type: 'apartment',
      isAirbnb: true,
      superhost: true,
      hasKitchen: true,
      stars: 4,
      rating: 9.4,
      ratingLabel: 'Superhost ⭐',
      reviewCount: 1420,
      distanceFromCenter: '100m de Calle Larios',
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80',
      nightlyRate: 25,
      totalPrice: 75,
      freeCancellation: true,
      breakfastIncluded: false,
      bookingPlatform: 'Airbnb',
      propertyType: 'Ático con terraza privada & cocina',
    },
    flightPrice: 34,
    hotelPrice: 75,
    totalPrice: 109,
    nights: 3,
    tripScore: 96,
    scores: { price: 100, hotel: 92, flight: 96, convenience: 94, destination: 95 },
    aiExplanation: 'El precio más bajo de todo el catálogo: solo 109 € con vuelo directo en 2h y ático Airbnb junto a la calle Larios con terraza.',
    tags: ['⭐ Escapada más barata (109€)', '✈️ Vuelo Directo 2h', '🏡 Airbnb Superhost', '☀️ Sol & Tapas'],
    vibe: 'sun',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 35,
      beerPrice: 2.0,
      mealPrice: 10.5,
      coffeePrice: 1.3,
      transportPrice: 1.4,
      costTier: 'low',
    },
    weather: { temp: 24, text: 'Soleado y caluroso', icon: '☀️' },
    itinerary: [
      {
        day: 1,
        title: 'Calle Larios, Alcazaba & Atardecer en Gibralfaro',
        morning: 'Llegada matutina, paseo por Calle Larios y aperitivo en El Pimpi.',
        afternoon: 'Subida a la Alcazaba y el Teatro Romano.',
        evening: 'Puestas de sol en el Castillo de Gibralfaro y tapeo por el centro.',
        tip: 'El tren de cercanías C1 conecta el aeropuerto con el centro en 12 minutos.',
      },
      {
        day: 2,
        title: 'Museo Picasso & Espetos en Pedregalejo',
        morning: 'Visita cultural al Museo Picasso Málaga y Centro Pompidou en el Muelle Uno.',
        afternoon: 'Paseo en bici hasta Pedregalejo para comer espetos de sardinas en la playa.',
        evening: 'Cóctel en una terraza con vistas a la Catedral.',
        tip: 'Alquila una bici municipal para recorrer todo el paseo marítimo.',
      },
      {
        day: 3,
        title: 'Mercado de Atarazanas & Playa de la Malagueta',
        morning: 'Desayuno de churros con chocolate en Casa Aranda y paseo por el Mercado de Atarazanas.',
        afternoon: 'Baño y relax en la playa de la Malagueta.',
        evening: 'Vuelo directo de vuelta a Canarias bien descansado.',
        tip: 'Lleva la toalla de mano, el clima de Málaga en otoño es perfecto para la playa.',
      },
    ],
    curatedActivity: { name: 'Entrada Museo Picasso Málaga', price: 12, duration: '2h', rating: 9.3 },
    activities: [
      { name: 'Entrada Museo Picasso Málaga', price: 12, duration: '2h', rating: 9.3 },
      { name: 'Paseo en catamarán al atardecer', price: 16, duration: '1.5h', rating: 9.1 },
    ],
    savedByUsers: 1120,
    priceDropped: true,
    previousPrice: 139,
  },
  {
    id: 'trip-svq-001',
    destination: {
      city: 'Sevilla',
      country: 'España',
      countryCode: 'ES',
      flag: '🇪🇸',
      image: 'https://images.unsplash.com/photo-1559564484-e48b3e040ff4?w=800&q=80',
      description: 'El embrujo de Andalucía. Plaza de España, tapas y arte.',
    },
    outboundFlight: {
      departure: '2026-10-12T07:45:00',
      arrival: '2026-10-12T11:00:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'SVQ', name: 'San Pablo', city: 'Sevilla' },
      airline: 'Ryanair',
      flightNumber: 'FR2855',
      duration: '2h 15m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-15T19:30:00',
      arrival: '2026-10-15T20:50:00',
      origin: { code: 'SVQ', name: 'San Pablo', city: 'Sevilla' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Ryanair',
      flightNumber: 'FR2856',
      duration: '2h 20m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Apartamento Palacio Santa Cruz Airbnb',
      type: 'apartment',
      isAirbnb: true,
      superhost: true,
      hasKitchen: true,
      stars: 4,
      rating: 9.3,
      ratingLabel: 'Superhost ⭐',
      reviewCount: 2190,
      distanceFromCenter: '150m de la Giralda',
      image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
      nightlyRate: 26,
      totalPrice: 78,
      freeCancellation: true,
      breakfastIncluded: false,
      bookingPlatform: 'Airbnb',
      propertyType: 'Apartamento con patio andaluz privado',
    },
    flightPrice: 38,
    hotelPrice: 78,
    totalPrice: 116,
    nights: 3,
    tripScore: 95,
    scores: { price: 98, hotel: 92, flight: 96, convenience: 94, destination: 95 },
    aiExplanation: 'Vuelo directo corto de solo 2h 15m y apartamento Airbnb en pleno Barrio de Santa Cruz a 3 minutos a pie de la Catedral.',
    tags: ['✈️ Directo 2h', '🏡 Airbnb Santa Cruz', '🏰 A 150m Giralda', '🥘 Tapas & Arte'],
    vibe: 'gastronomy',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 36,
      beerPrice: 1.8,
      mealPrice: 11.0,
      coffeePrice: 1.3,
      transportPrice: 1.4,
      costTier: 'low',
    },
    weather: { temp: 25, text: 'Soleado y despejado', icon: '☀️' },
    itinerary: [
      {
        day: 1,
        title: 'Catedral, Giralda & Barrio de Santa Cruz',
        morning: 'Llegada rápida, subida a las rampas de la Giralda y visita a la Catedral.',
        afternoon: 'Pérdida intencionada por el laberinto de callejuelas en Santa Cruz.',
        evening: 'Tapeo de solomillo al whisky y espinacas con garbanzos en El Rinconcillo.',
        tip: 'El autobús EA conecta el aeropuerto con Plaza de Armas por 4 €.',
      },
      {
        day: 2,
        title: 'Real Alcázar & Plaza de España',
        morning: 'Visita de cine al Real Alcázar y sus jardines de ensueño.',
        afternoon: 'Paseo en barca por la majestuosa Plaza de España y Parque de María Luisa.',
        evening: 'Espectáculo de flamenco auténtico en el barrio de Triana cruzando el puente.',
        tip: 'Compra la entrada al Alcázar por internet para evitar 1 hora de cola.',
      },
      {
        day: 3,
        title: 'Las Setas de Sevilla & Despedida',
        morning: 'Paseo por la pasarela de Las Setas de la Encarnación con vistas 360º.',
        afternoon: 'Compras en calle Sierpes y merienda de tortas de aceite.',
        evening: 'Vuelo de vuelta a las islas al anochecer.',
        tip: 'Sube a Las Setas por la mañana para tener luz perfecta para fotos.',
      },
    ],
    curatedActivity: { name: 'Real Alcázar (acceso prioritario)', price: 19, duration: '2.5h', rating: 9.7 },
    activities: [
      { name: 'Real Alcázar (acceso prioritario)', price: 19, duration: '2.5h', rating: 9.7 },
      { name: 'Espectáculo flamenco en Triana', price: 22, duration: '1.5h', rating: 9.4 },
    ],
    savedByUsers: 645,
  },
  {
    id: 'trip-rak-001',
    destination: {
      city: 'Marrakech',
      country: 'Marruecos',
      countryCode: 'MA',
      flag: '🇲🇦',
      image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800&q=80',
      description: 'Zocos mágicos, palacios de las mil y una noches y riads de ensueño.',
    },
    outboundFlight: {
      departure: '2026-10-13T10:00:00',
      arrival: '2026-10-13T12:20:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'RAK', name: 'Menara', city: 'Marrakech' },
      airline: 'Ryanair',
      flightNumber: 'FR3180',
      duration: '2h 20m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-16T15:40:00',
      arrival: '2026-10-16T18:00:00',
      origin: { code: 'RAK', name: 'Menara', city: 'Marrakech' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Ryanair',
      flightNumber: 'FR3181',
      duration: '2h 20m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Riad Boutique Medina Airbnb Superhost',
      type: 'apartment',
      isAirbnb: true,
      superhost: true,
      stars: 4,
      rating: 9.5,
      ratingLabel: 'Superhost ⭐',
      reviewCount: 1680,
      distanceFromCenter: '300m de Plaza Jemaa el-Fna',
      image: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?w=600&q=80',
      nightlyRate: 31,
      totalPrice: 93,
      freeCancellation: true,
      breakfastIncluded: true,
      bookingPlatform: 'Airbnb',
      propertyType: 'Riad tradicional privado con piscina',
    },
    flightPrice: 42,
    hotelPrice: 93,
    totalPrice: 135,
    nights: 3,
    tripScore: 95,
    scores: { price: 96, hotel: 95, flight: 94, convenience: 90, destination: 98 },
    aiExplanation: 'Experiencia exótica inolvidable. Vuelo directo de solo 2h 20m y Riad completo en Airbnb con patio andalusí y desayuno marroquí incluido.',
    tags: ['✨ Experiencia Exótica', '✈️ Vuelo Directo 2h', '🏡 Riad Airbnb', '🥐 Desayuno Incluido'],
    vibe: 'culture',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 28,
      beerPrice: 3.5,
      mealPrice: 7.5,
      coffeePrice: 1.0,
      transportPrice: 0.8,
      costTier: 'low',
    },
    weather: { temp: 27, text: 'Soleado y muy cálido', icon: '☀️' },
    itinerary: [
      {
        day: 1,
        title: 'Llegada, Riad & Espectáculo en Jemaa el-Fna',
        morning: 'Llegada al aeropuerto Menara, bienvenida en el riad con té a la menta.',
        afternoon: 'Paseo por la Mezquita Koutoubia y primeros regateos en los zocos.',
        evening: 'Cena en la terraza de Café de France viendo la ebullición de la Plaza Jemaa el-Fna.',
        tip: 'Lleva dinero en efectivo (dírhams) para los puestos de artesanía.',
      },
      {
        day: 2,
        title: 'Jardín Majorelle, Palacio Bahía & Hammam',
        morning: 'Visita matutina al oasis azul cobalto del Jardín Majorelle y Museo Yves Saint Laurent.',
        afternoon: 'Visita a los mosaicos del Palacio Bahía y las Tumbas Saadíes.',
        evening: 'Sesión de relax en un hammam tradicional con jabón negro y exfoliación.',
        tip: 'Compra las entradas del Jardín Majorelle con antelación en su web oficial.',
      },
      {
        day: 3,
        title: 'Madraza Ben Youssef & Despedida',
        morning: 'Fotografías en la arquitectura islámica de la Madraza Ben Youssef.',
        afternoon: 'Últimas compras de especias, aceite de argán y babuchas.',
        evening: 'Traslado al aeropuerto y vuelo directo a Canarias.',
        tip: 'El taxi al aeropuerto desde la Medina tiene tarifa fija pactada.',
      },
    ],
    curatedActivity: { name: 'Excursión en camello por el Palmeral', price: 18, duration: '2h', rating: 9.1 },
    activities: [
      { name: 'Excursión en camello por el Palmeral', price: 18, duration: '2h', rating: 9.1 },
      { name: 'Tour guiado por los Zocos de la Medina', price: 20, duration: '3h', rating: 9.4 },
    ],
    savedByUsers: 950,
  },
  {
    id: 'trip-lis-001',
    destination: {
      city: 'Lisboa',
      country: 'Portugal',
      countryCode: 'PT',
      flag: '🇵🇹',
      image: 'https://images.unsplash.com/photo-1509840841025-9088ba78a826?w=800&q=80',
      description: 'Tranvías amarillos, fado, miradores románticos y pasteles de Belém.',
    },
    outboundFlight: {
      departure: '2026-10-15T08:30:00',
      arrival: '2026-10-15T11:00:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'LIS', name: 'Humberto Delgado', city: 'Lisboa' },
      airline: 'TAP Air Portugal',
      flightNumber: 'TP1124',
      duration: '2h 30m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-18T18:15:00',
      arrival: '2026-10-18T20:45:00',
      origin: { code: 'LIS', name: 'Humberto Delgado', city: 'Lisboa' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'TAP Air Portugal',
      flightNumber: 'TP1125',
      duration: '2h 30m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Loft Alfama Mirador Airbnb Plus',
      type: 'apartment',
      isAirbnb: true,
      superhost: true,
      hasKitchen: true,
      stars: 4,
      rating: 9.4,
      ratingLabel: 'Superhost ⭐',
      reviewCount: 3840,
      distanceFromCenter: '200m de Santa Justa',
      image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80',
      nightlyRate: 30,
      totalPrice: 90,
      freeCancellation: true,
      breakfastIncluded: false,
      bookingPlatform: 'Airbnb',
      propertyType: 'Loft histórico con cocina & mirador',
    },
    flightPrice: 48,
    hotelPrice: 90,
    totalPrice: 138,
    nights: 3,
    tripScore: 94,
    scores: { price: 92, hotel: 94, flight: 96, convenience: 94, destination: 96 },
    aiExplanation: 'Uno de los destinos favoritos. Vuelo directo con TAP y loft Airbnb en el corazón de Alfama con vistas al Tajo.',
    tags: ['✈️ Directo TAP', '🏡 Airbnb Plus', '🍷 Fado & Vistas', '🚃 Tranvía 28'],
    vibe: 'romantic',
    priceTrend: 'stable',
    destinationCost: {
      dailyAverage: 38,
      beerPrice: 2.0,
      mealPrice: 11.5,
      coffeePrice: 1.0,
      transportPrice: 1.5,
      costTier: 'medium',
    },
    weather: { temp: 22, text: 'Soleado con brisa', icon: '🌤️' },
    itinerary: [
      {
        day: 1,
        title: 'Alfama, Tranvía 28 & Noche de Fado',
        morning: 'Llegada, check-in en el loft y paseo en el mítico Tranvía 28.',
        afternoon: 'Subida al Castillo de San Jorge y mirador de Santa Luzia.',
        evening: 'Cena con fado en vivo en una taberna tradicional de Alfama.',
        tip: 'El metro rojo te conecta directo del aeropuerto al centro en 20 min.',
      },
      {
        day: 2,
        title: 'Belém, Monasterio de los Jerónimos & Pastéis',
        morning: 'Tranvía hacia Belém, visita a los Jerónimos y Torre de Belém.',
        afternoon: 'Degustación de los auténticos Pastéis de Belém recién horneados.',
        evening: 'Atardecer junto al río Tajo en el Monumento a los Descubrimientos.',
        tip: 'Pide los pastéis con canela y azúcar glas por encima.',
      },
      {
        day: 3,
        title: 'Chiado, Elevador de Santa Justa & Regreso',
        morning: 'Paseo elegante por el Chiado y café en A Brasileira.',
        afternoon: 'Panorámica desde el Elevador de Santa Justa.',
        evening: 'Vuelo directo de regreso a Canarias.',
        tip: 'La tarjeta Viva Viagem recargable sirve para metro, buses y tranvías.',
      },
    ],
    curatedActivity: { name: 'Excursión a Sintra y Palacio da Pena', price: 28, duration: '5h', rating: 9.5 },
    activities: [
      { name: 'Excursión a Sintra y Palacio da Pena', price: 28, duration: '5h', rating: 9.5 },
      { name: 'Paseo en barco tradicional por el Tajo', price: 19, duration: '2h', rating: 9.2 },
    ],
    savedByUsers: 810,
  },
  {
    id: 'trip-vlc-001',
    destination: {
      city: 'Valencia',
      country: 'España',
      countryCode: 'ES',
      flag: '🇪🇸',
      image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=800&q=80',
      description: 'Ciudad de las Artes y las Ciencias, paella auténtica y playa.',
    },
    outboundFlight: {
      departure: '2026-10-12T08:15:00',
      arrival: '2026-10-12T12:05:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'VLC', name: 'Manises', city: 'Valencia' },
      airline: 'Ryanair',
      flightNumber: 'FR2830',
      duration: '2h 50m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-15T20:30:00',
      arrival: '2026-10-15T22:25:00',
      origin: { code: 'VLC', name: 'Manises', city: 'Valencia' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Ryanair',
      flightNumber: 'FR2831',
      duration: '2h 55m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Apartamento Ruzafa Boho Airbnb Superhost',
      type: 'apartment',
      isAirbnb: true,
      superhost: true,
      hasKitchen: true,
      stars: 4,
      rating: 9.3,
      ratingLabel: 'Superhost ⭐',
      reviewCount: 1950,
      distanceFromCenter: '300m de Ruzafa centro',
      image: 'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=600&q=80',
      nightlyRate: 27,
      totalPrice: 81,
      freeCancellation: true,
      breakfastIncluded: false,
      bookingPlatform: 'Airbnb',
      propertyType: 'Apartamento completo con balcón',
    },
    flightPrice: 40,
    hotelPrice: 81,
    totalPrice: 121,
    nights: 3,
    tripScore: 94,
    scores: { price: 96, hotel: 92, flight: 94, convenience: 93, destination: 93 },
    aiExplanation: 'Planazo mediterráneo. Vuelo directo y apartamento Airbnb en el vibrante barrio de Ruzafa a un precio imbatible.',
    tags: ['✈️ Directo', '🏡 Airbnb Ruzafa', '🥘 Paella Valenciana', '🏛️ Ciudad de las Artes'],
    vibe: 'gastronomy',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 37,
      beerPrice: 2.2,
      mealPrice: 12.0,
      coffeePrice: 1.4,
      transportPrice: 1.5,
      costTier: 'medium',
    },
    weather: { temp: 23, text: 'Soleado y templado', icon: '☀️' },
    itinerary: [
      {
        day: 1,
        title: 'Centro Histórico, Lonja & Mercado Central',
        morning: 'Llegada matutina, visita al Mercado Central y la Lonja de la Seda.',
        afternoon: 'Subida a las Torres de Serranos y paseo por el Barrio del Carmen.',
        evening: 'Cena de tapas creativas y cervezas en el barrio de Ruzafa.',
        tip: 'El metro te lleva de Manises al centro en 20 minutos.',
      },
      {
        day: 2,
        title: 'Ciudad de las Artes, Oceanogràfic & Paella',
        morning: 'Recorrido futurista por la Ciudad de las Artes y el Oceanogràfic.',
        afternoon: 'Auténtica paella valenciana a leña de naranjo en El Palmar (Albufera).',
        evening: 'Paseo en barca al atardecer por la Albufera de Valencia.',
        tip: 'La paella tradicional lleva pollo, conejo y judías verdes (bajoqueta).',
      },
      {
        day: 3,
        title: 'Jardines del Turia & Playa de la Malvarrosa',
        morning: 'Paseo en bicicleta por el antiguo cauce del río Turia.',
        afternoon: 'Paseo por la playa de la Malvarrosa y copa de horchata artesanal.',
        evening: 'Vuelo directo de regreso a las islas.',
        tip: 'Prueba la horchata con fartons en Santa Catalina.',
      },
    ],
    curatedActivity: { name: 'Entrada Ciudad de las Artes y las Ciencias', price: 21, duration: '3h', rating: 9.3 },
    activities: [
      { name: 'Entrada Ciudad de las Artes y las Ciencias', price: 21, duration: '3h', rating: 9.3 },
      { name: 'Paseo en barca al atardecer en la Albufera', price: 12, duration: '1.5h', rating: 9.5 },
    ],
    savedByUsers: 590,
  },
  {
    id: 'trip-fco-001',
    destination: {
      city: 'Roma',
      country: 'Italia',
      countryCode: 'IT',
      flag: '🇮🇹',
      image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
      description: 'La Ciudad Eterna. Coliseo, Fontana di Trevi y la mejor pasta del mundo.',
    },
    outboundFlight: {
      departure: '2026-10-14T06:00:00',
      arrival: '2026-10-14T11:20:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'FCO', name: 'Fiumicino', city: 'Roma' },
      airline: 'Wizz Air',
      flightNumber: 'W63140',
      duration: '4h 20m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-17T18:00:00',
      arrival: '2026-10-17T21:40:00',
      origin: { code: 'FCO', name: 'Fiumicino', city: 'Roma' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Wizz Air',
      flightNumber: 'W63141',
      duration: '4h 40m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Hotel Nazionale Roma 4★',
      type: 'hotel',
      stars: 4,
      rating: 8.8,
      ratingLabel: 'Fabuloso',
      reviewCount: 4210,
      distanceFromCenter: '150m de Plaza Navona',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      nightlyRate: 34,
      totalPrice: 102,
      freeCancellation: true,
      breakfastIncluded: true,
      bookingPlatform: 'Booking',
      propertyType: 'Hotel 4 Estrellas',
    },
    flightPrice: 56,
    hotelPrice: 102,
    totalPrice: 158,
    nights: 3,
    tripScore: 93,
    scores: { price: 90, hotel: 94, flight: 92, convenience: 92, destination: 99 },
    aiExplanation: 'Roma al mejor precio. Vuelo directo y hotel 4 estrellas junto a Plaza Navona con desayuno italiano incluido.',
    tags: ['✈️ Vuelo Directo', '🏨 4 Estrellas', '🍝 Carbonara Auténtica', '🏛️ A 150m Navona'],
    vibe: 'culture',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 48,
      beerPrice: 3.5,
      mealPrice: 15.0,
      coffeePrice: 1.4,
      transportPrice: 1.5,
      costTier: 'high',
    },
    weather: { temp: 21, text: 'Soleado con brisa', icon: '🌤️' },
    itinerary: [
      {
        day: 1,
        title: 'Coliseo, Foro Romano & Trastevere',
        morning: 'Llegada, check-in y visita con audioguía al Coliseo y Foro Romano.',
        afternoon: 'Paseo por el Circo Máximo y la colina del Aventino (cerradura mágica).',
        evening: 'Cena de pasta cacio e pepe en el animado barrio de Trastevere.',
        tip: 'El tren Leonardo Express conecta Fiumicino con Termini en 30 minutos.',
      },
      {
        day: 2,
        title: 'Fontana di Trevi, Panteón & Vaticano',
        morning: 'Moneda en la Fontana di Trevi a primera hora y asombro en el Panteón de Agripa.',
        afternoon: 'Plaza de San Pedro en el Vaticano y Museos Vaticanos.',
        evening: 'Helado artesanal en Giolitti y paseo nocturno por Plaza Navona iluminada.',
        tip: 'Las fuentes de agua de Roma (nasoni) tienen agua potable y deliciosa gratis.',
      },
      {
        day: 3,
        title: 'Piazza di Spagna & Vuelo de Regreso',
        morning: 'Escalinata de Piazza di Spagna y compras por Vía del Corso.',
        afternoon: 'Último espresso y pizza al taglio.',
        evening: 'Vuelo directo de vuelta a Canarias.',
        tip: 'Guarda tiempo para el control de seguridad de Fiumicino.',
      },
    ],
    curatedActivity: { name: 'Coliseo, Foro y Palatino sin colas', price: 24, duration: '3h', rating: 9.6 },
    activities: [
      { name: 'Coliseo, Foro y Palatino sin colas', price: 24, duration: '3h', rating: 9.6 },
      { name: 'Museos Vaticanos y Capilla Sixtina', price: 29, duration: '3.5h', rating: 9.7 },
    ],
    savedByUsers: 1430,
  },
  {
    id: 'trip-ory-001',
    destination: {
      city: 'París',
      country: 'Francia',
      countryCode: 'FR',
      flag: '🇫🇷',
      image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
      description: 'La Ciudad de la Luz. Torre Eiffel, el Sena, museos y gastronomía.',
    },
    outboundFlight: {
      departure: '2026-10-13T09:00:00',
      arrival: '2026-10-13T14:15:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'ORY', name: 'París Orly', city: 'París' },
      airline: 'Vueling',
      flightNumber: 'VY8220',
      duration: '4h 15m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-16T15:30:00',
      arrival: '2026-10-16T18:45:00',
      origin: { code: 'ORY', name: 'París Orly', city: 'París' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Vueling',
      flightNumber: 'VY8221',
      duration: '4h 15m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Hotel Le Marais Boutique',
      type: 'hotel',
      stars: 3,
      rating: 8.7,
      ratingLabel: 'Fabuloso',
      reviewCount: 3100,
      distanceFromCenter: '400m de Plaza de los Vosgos',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
      nightlyRate: 38,
      totalPrice: 114,
      freeCancellation: true,
      breakfastIncluded: true,
      bookingPlatform: 'Booking',
      propertyType: 'Hotel Boutique',
    },
    flightPrice: 62,
    hotelPrice: 114,
    totalPrice: 176,
    nights: 3,
    tripScore: 92,
    scores: { price: 88, hotel: 94, flight: 94, convenience: 92, destination: 99 },
    aiExplanation: 'París dentro de tu presupuesto. Vuelo directo a Orly y hotel boutique en Le Marais con desayuno parisino incluido.',
    tags: ['✈️ Directo a Orly', '🥐 Desayuno Incluido', '🗼 Torre Eiffel', '🎨 Barrio Le Marais'],
    vibe: 'romantic',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 52,
      beerPrice: 4.5,
      mealPrice: 17.0,
      coffeePrice: 2.2,
      transportPrice: 2.1,
      costTier: 'high',
    },
    weather: { temp: 18, text: 'Templado y otoñal', icon: '🍂' },
    itinerary: [
      {
        day: 1,
        title: 'Torre Eiffel, Sena & Barrio Latino',
        morning: 'Llegada a Orly, metro 14 directo al centro y check-in en Le Marais.',
        afternoon: 'Paseo por los Campos Elíseos y vistas a la Torre Eiffel desde Trocadéro.',
        evening: 'Paseo en barco por el Sena y cena de crepes en el Barrio Latino.',
        tip: 'La línea 14 de metro conecta Orly con Châtelet en solo 25 minutos.',
      },
      {
        day: 2,
        title: 'Museo del Louvre, Montmartre & Sacré-Cœur',
        morning: 'Visita matutina a la Gioconda y esculturas en el Museo del Louvre.',
        afternoon: 'Paseo bohemio por Montmartre y la plaza de los pintores (Place du Tertre).',
        evening: 'Atardecer desde las escaleras de la Basílica del Sacré-Cœur.',
        tip: 'Reserva la franja horaria del Louvre con antelación obligatoria.',
      },
      {
        day: 3,
        title: 'Notre Dame, Sainte-Chapelle & Regreso',
        morning: 'Visita exterior a Notre Dame y las increíbles vidrieras de Sainte-Chapelle.',
        afternoon: 'Compras de macarons en Ladurée y paseo por los Jardines de Luxemburgo.',
        evening: 'Vuelo directo de vuelta a Canarias.',
        tip: 'Los jardines de Luxemburgo son un oasis para descansar los pies.',
      },
    ],
    curatedActivity: { name: 'Crucero por el Sena de 1 hora', price: 17, duration: '1h', rating: 9.4 },
    activities: [
      { name: 'Crucero por el Sena de 1 hora', price: 17, duration: '1h', rating: 9.4 },
      { name: 'Entrada sin colas al Museo del Louvre', price: 22, duration: '3h', rating: 9.7 },
    ],
    savedByUsers: 1650,
  },
  {
    id: 'trip-stn-001',
    destination: {
      city: 'Londres',
      country: 'Reino Unido',
      countryCode: 'GB',
      flag: '🇬🇧',
      image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
      description: 'Big Ben, museos gratuitos de clase mundial y mercados callejeros.',
    },
    outboundFlight: {
      departure: '2026-10-13T07:00:00',
      arrival: '2026-10-13T11:45:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'STN', name: 'Stansted', city: 'Londres' },
      airline: 'Ryanair',
      flightNumber: 'FR1820',
      duration: '4h 45m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-16T16:30:00',
      arrival: '2026-10-16T21:15:00',
      origin: { code: 'STN', name: 'Stansted', city: 'Londres' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Ryanair',
      flightNumber: 'FR1821',
      duration: '4h 45m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'The Hoxton Shoreditch Hotel',
      type: 'hotel',
      stars: 4,
      rating: 8.9,
      ratingLabel: 'Fabuloso',
      reviewCount: 3890,
      distanceFromCenter: 'Shoreditch centro',
      image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80',
      nightlyRate: 36,
      totalPrice: 108,
      freeCancellation: true,
      breakfastIncluded: false,
      bookingPlatform: 'Booking',
      propertyType: 'Hotel de Diseño',
    },
    flightPrice: 52,
    hotelPrice: 108,
    totalPrice: 160,
    nights: 3,
    tripScore: 91,
    scores: { price: 88, hotel: 92, flight: 94, convenience: 90, destination: 96 },
    aiExplanation: 'Escapada cosmopolita. Vuelo directo y hotel de diseño en el vibrante barrio de Shoreditch para vivir Londres a tope.',
    tags: ['✈️ Directo', '🏨 Hotel Hoxton', '🎭 Museos Gratis', '🛍️ Mercados'],
    vibe: 'nightlife',
    priceTrend: 'stable',
    destinationCost: {
      dailyAverage: 55,
      beerPrice: 5.5,
      mealPrice: 18.0,
      coffeePrice: 3.2,
      transportPrice: 3.5,
      costTier: 'high',
    },
    weather: { temp: 16, text: 'Fresco y cambiante', icon: '⛅' },
    itinerary: [
      {
        day: 1,
        title: 'Big Ben, London Eye & Soho',
        morning: 'Llegada, Stansted Express al centro y paseo junto al Big Ben y el Parlamento.',
        afternoon: 'Paseo por Westminster Bridge y Trafalgar Square.',
        evening: 'Ruta de pubs tradicionales y cena asiática en Chinatown / Soho.',
        tip: 'Usa tu tarjeta contactless en el metro para tener la tarifa más barata con tope diario.',
      },
      {
        day: 2,
        title: 'Museo Británico, Camden Market & Tower Bridge',
        morning: 'Visita a la Piedra Rosetta en el Museo Británico (entrada gratuita).',
        afternoon: 'Comida callejera y compras vintage en Camden Town.',
        evening: 'Paseo al anochecer cruzando el iluminado Tower Bridge.',
        tip: 'La mayoría de museos de Londres son de entrada 100% gratuita.',
      },
      {
        day: 3,
        title: 'Borough Market, Sky Garden & Regreso',
        morning: 'Desayuno gourmet en Borough Market con productos locales.',
        afternoon: 'Vistas panorámicas 360º de Londres gratis en el mirador Sky Garden.',
        evening: 'Vuelo directo de vuelta a las islas.',
        tip: 'Reserva la entrada gratuita al Sky Garden 3 semanas antes en su web.',
      },
    ],
    curatedActivity: { name: 'Entrada London Eye con vistas', price: 29, duration: '45m', rating: 9.3 },
    activities: [
      { name: 'Entrada London Eye con vistas', price: 29, duration: '45m', rating: 9.3 },
      { name: 'Tour de Jack el Destripador', price: 16, duration: '2h', rating: 9.1 },
    ],
    savedByUsers: 1210,
  },
  {
    id: 'trip-bgy-001',
    destination: {
      city: 'Milán',
      country: 'Italia',
      countryCode: 'IT',
      flag: '🇮🇹',
      image: 'https://images.unsplash.com/photo-1513581166391-887a96ddeafd?w=800&q=80',
      description: 'Capital de la moda, Duomo imponente y aperitivo en Navigli.',
    },
    outboundFlight: {
      departure: '2026-10-14T06:45:00',
      arrival: '2026-10-14T12:00:00',
      origin: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      destination: { code: 'BGY', name: 'Milán Bérgamo', city: 'Milán' },
      airline: 'Ryanair',
      flightNumber: 'FR4250',
      duration: '4h 15m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    returnFlight: {
      departure: '2026-10-17T17:30:00',
      arrival: '2026-10-17T20:55:00',
      origin: { code: 'BGY', name: 'Milán Bérgamo', city: 'Milán' },
      destination: { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife' },
      airline: 'Ryanair',
      flightNumber: 'FR4251',
      duration: '4h 25m',
      stops: 0,
      cabinBagIncluded: true,
      checkedBagIncluded: false,
    },
    hotel: {
      name: 'Hotel Milano Duomo Navigli',
      type: 'hotel',
      stars: 4,
      rating: 8.7,
      ratingLabel: 'Fabuloso',
      reviewCount: 2980,
      distanceFromCenter: '400m de los canales Navigli',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      nightlyRate: 31,
      totalPrice: 93,
      freeCancellation: true,
      breakfastIncluded: true,
      bookingPlatform: 'Booking',
      propertyType: 'Hotel 4 Estrellas',
    },
    flightPrice: 48,
    hotelPrice: 93,
    totalPrice: 141,
    nights: 3,
    tripScore: 93,
    scores: { price: 92, hotel: 94, flight: 92, convenience: 92, destination: 95 },
    aiExplanation: 'Milán y Bérgamo en un solo viaje. Vuelo directo y hotel 4 estrellas con desayuno buffet junto a los canales de Navigli.',
    tags: ['✈️ Directo', '🏨 4 Estrellas', '🥐 Desayuno Buffet', '🍸 Aperitivo Navigli'],
    vibe: 'gastronomy',
    priceTrend: 'lowest',
    destinationCost: {
      dailyAverage: 46,
      beerPrice: 4.0,
      mealPrice: 14.5,
      coffeePrice: 1.5,
      transportPrice: 2.0,
      costTier: 'medium',
    },
    weather: { temp: 19, text: 'Agradable y templado', icon: '🌤️' },
    itinerary: [
      {
        day: 1,
        title: 'Duomo de Milán, Galería & Aperitivo en Navigli',
        morning: 'Llegada, autobús de Bérgamo a Milán Central y admiración del Duomo.',
        afternoon: 'Paseo bajo la cúpula de la Galería Vittorio Emanuele II y Teatro alla Scala.',
        evening: 'El clásico aperitivo milanés en los canales de Navigli (buffet libre de comida con tu bebida).',
        tip: 'El autobús Terravision de Bérgamo a Milán sale cada 20 min y cuesta 6 €.',
      },
      {
        day: 2,
        title: 'Castillo Sforzesco, Brera & Lago de Como',
        morning: 'Paseo por el Castillo Sforzesco y las galerías de arte del bohemio barrio de Brera.',
        afternoon: 'Escapada en tren de 35 min al Lago de Como para navegar en barco.',
        evening: 'Cena con auténtico risotto a la milanesa y ossobuco.',
        tip: 'El tren regional a Como cuesta solo 5 € desde Milano Cadorna.',
      },
      {
        day: 3,
        title: 'Città Alta de Bérgamo & Regreso',
        morning: 'Visita de cuento a la Ciudad Alta medieval de Bérgamo con su funicular.',
        afternoon: 'Almuerzo de polenta taragna en la Piazza Vecchia de Bérgamo.',
        evening: 'Vuelo directo de vuelta a Canarias.',
        tip: 'Bérgamo Città Alta está a solo 15 minutos en autobús del aeropuerto.',
      },
    ],
    curatedActivity: { name: 'Terrazas del Duomo de Milán en ascensor', price: 16, duration: '1.5h', rating: 9.5 },
    activities: [
      { name: 'Terrazas del Duomo de Milán en ascensor', price: 16, duration: '1.5h', rating: 9.5 },
      { name: 'Excursión de un día al Lago de Como', price: 34, duration: '8h', rating: 9.6 },
    ],
    savedByUsers: 770,
  },
];

import { DESTINATION_DIRECTORY } from './destination-data';

export const POPULAR_DESTINATIONS = [
  'OPO', 'AGP', 'BCN', 'MAD', 'SVQ', 'RAK', 'ROM', 'LIS'
].map((code) => {
  const meta = DESTINATION_DIRECTORY[code] || DESTINATION_DIRECTORY['BCN'];
  return {
    city: meta.city,
    country: meta.country,
    flag: meta.flag,
    image: meta.image,
    from: meta.hotelNightly * 3 + 35,
  };
});

